### ISSUE TITLE
Call to undefined method Http\Client\Exception\RequestException::getResponse() (/var/www/vendor/maclof/kubernetes-client/src/Client.php:427)

### ISSUE THREAD

**Issue by blieb** [maclof/kubernetes-client#110]
I did upgrade to the latest version of kubernetes client, after that I'm getting this error:

```
Error: [Error] Call to undefined method Http\Client\Exception\RequestException::getResponse() (/var/www/vendor/maclof/kubernetes-client/src/Client.php:427)
#0 /var/www/vendor/maclof/kubernetes-client/src/Repositories/Repository.php(79): Maclof\Kubernetes\Client->sendRequest('GET', '/deployments', Array, NULL, true, 'apps/v1', Array)
#1 /var/www/vendor/maclof/kubernetes-client/src/Repositories/Repository.php(255): Maclof\Kubernetes\Repositories\Repository->sendRequest('GET', '/deployments', Array, NULL, true)
#2 /var/www/vendor/maclof/kubernetes-client/src/Repositories/Repository.php(265): Maclof\Kubernetes\Repositories\Repository->find()
#3 /var/www/vendor/maclof/kubernetes-client/src/Repositories/Repository.php(305): Maclof\Kubernetes\Repositories\Repository->first()
#4 /var/www/vendor/maclof/kubernetes-client/src/Repositories/Repository.php(146): Maclof\Kubernetes\Repositories\Repository->exists('peoplecounter-5...')

```

it appears that guzzle giving an exception that it is unable to connect due ssl errors. so it is not possible to call getResponse on that exception. 

I've logged the error on the exception there. it says: "cURL error 60: SSL certificate problem: unable to get local issuer certificate".

**Comment by maclof** [comment]
This isn't a bug with the package, you need to either provide client TLS certificates or disable TLS verification, e.g. https://github.com/maclof/kubernetes-client#insecure-https-ca-certificate-verification-disabled

**Comment by blieb** [comment]
> This isn't a bug with the package, you need to either provide client TLS certificates or disable TLS verification, e.g. https://github.com/maclof/kubernetes-client#insecure-https-ca-certificate-verification-disabled
> 
> 

Hmm yes I did find that, but That it gives this error is a bug with the package I think? It should give the ssl error. Not that it can not call the function. Now I had to find the issue by logging the exception in the package. But it is working for me now. 😊

**Comment by maikfr** [comment]
Hello,
whatever the actual underlying problem was: calling getResponse method which is undefined on the given interface Http\Client\Exception\TransferException, also seem to be a bug to me. Please consider https://github.com/php-http/httplug/blob/2.3.0/src/Exception/TransferException.php

Thank you in advance.
