### ISSUE TITLE
BaseUri doesn't work properly.

### ISSUE THREAD

**Issue by tamaspanczel** [maclof/kubernetes-client#35]
If kubernetes master url contains path like `http://localhost/kubernetes/` then baseUri doesn't work properly because it calls `http://localhost/v1/api/...` instead of `http://localhost/kubernetes/v1/api/...` in `Client.php`:
```
public function sendRequest($method, $uri, $query = [], $body = [], $namespace = true, $apiVersion = null)
{
  $baseUri = $apiVersion ? '/apis/' . $apiVersion : '/api/' . $this->apiVersion;
```

**Comment by maclof** [comment]
How are you deploying Kubernetes if your API is nested under a /kubernetes/ path? I've not seen this before

**Comment by tamaspanczel** [comment]
We are using Rancher and our cluster k8s url is:
`https://domain.com/k8s/clusters/c-cxwjp/`

**Comment by jamesmcminn96** [comment]
Have run into the same issue, based on RFC3986, the guzzle client is being created incorrectly such that only the host will be used from the `master` parameter of the k8s Client, and dropping the path.

@tamaspanczel, before I submit a PR to patch this have you had any work arounds?

**Comment by maclof** [comment]
What happens if you initialise the client like the following?

```php
$client = new Client([
	'master' => 'https://domain.com/k8s/clusters/c-cxwjp',
]);
```

According to the Guzzle client documentation the requests should then be relative to that URL?

**Comment by maclof** [comment]
Nevermind I see the problem, I've pushed a commit to resolve this

**Comment by jamesmcminn96** [comment]
Thanks @maclof!
