### ISSUE TITLE
Endpoints support

### ISSUE THREAD

**Issue by ivanjaros** [maclof/kubernetes-client#4]
Hi,
any plans on adding support for endpoints?

**Comment by maclof** [comment]
Hey Ivan,

No problem, I should be able to get endpoints support in today, I should have done this already.

**Comment by maclof** [comment]
Hey @ivanjaros 

I have now added support for endpoints, using an example such as the following:

```php
$endpoint = new Endpoint([
	'metadata' => [
		'name'      => 'test',
		'namespace' => 'default',
	],
	'subsets' => [
		[
			'addresses' => [
				[
					'ip' => '10.0.0.1',
				],
			],
			'ports' => [
				[
					'port'     => 80,
					'protocol' => 'TCP',
				],
			],
		],
		[
			'addresses' => [
				[
					'ip' => '10.0.0.2',
				],
			],
			'ports' => [
				[
					'port'     => 80,
					'protocol' => 'TCP',
				],
			],
		],
	],
]);

$client->endpoints()->create($endpoint);
```

I am currently undecided on whether or not I will name the model "Endpoint" or "Endpoints", the Kubernetes object it creates uses the plural version which is different from the rest, so I may change it to match.

Let me know if you find any issues with this and I'll fix them up ASAP.
