### ISSUE TITLE
Certificate kind

### ISSUE THREAD

**Issue by momon** [maclof/kubernetes-client#40]
Hello, I apologize if this question feels out of place but I am not sure where else to ask.  I've used your API to develop an app and find myself somewhat stuck on trying to deploy "Certificate kind" of yaml files.

For reference, my app relies on this: https://github.com/ahmetb/gke-letsencrypt/blob/master/50-get-a-certificate.md which is the process I've implemented for generating SSL certificates using letsencrypt.

This process relies on deploying these kind: Certificate yaml files and I am trying to figure out how I could achieve the same using your API.

I appreciate the direction and apologize if the question is out of place.  This is my first kubernetes project so I am in a learning curve at the moment.

Thanks!

**Comment by maclof** [comment]
@momon no problem at all, we do not support the Certificate resource yet but I’ll take a look tonight and see if I can get it added for you. I’ll then update the readme with an example

**Comment by momon** [comment]
@maclof that's absolutely fantastic!  I was getting ready to do all sort of shenanigans via command line in order to get that working as that's the only deployment I am missing in the application being so far invested already using your API so I massively appreciate the prompt response and attention, so I will just wait for an update!

Thanks again bud!

Cheers.

**Comment by maclof** [comment]
Hey mate, do you have a link to the API reference for this? Or is this not built into the core Kubernetes project, e.g. is it an addon?

**Comment by momon** [comment]
> 
> 
> Hey mate, do you have a link to the API reference for this? Or is this not built into the core Kubernetes project, e.g. is it an addon?

TY for the reply.  I am not 100% sure if this is what you need but have a look here:

http://docs.cert-manager.io/en/latest/reference/api-docs/index.html#certificate-v1alpha1

This is referenced by this:

https://github.com/ahmetb/gke-letsencrypt/blob/master/50-get-a-certificate.md

And the latter link is the process I've implemented for enabling Letsencrypt on the cluster to automatically have certificates generate and renew on the containers that need it.

I apologize if that's not a straightforward answer or the exact info you need but I am relatively new to Kubernetes so I am just now starting to learn all the bits and pieces.

Thanks!

**Comment by maclof** [comment]
@momon unfortunately I don't think this package will add support because it's not built directly into Kubernetes, it is an addon service.

However you should be able to use the client request methods directly to perform the API requests

I would take a look at this method:
https://github.com/maclof/kubernetes-client/blob/master/src/Client.php#L321

You can see some examples of the methods usage here:
https://github.com/maclof/kubernetes-client/blob/master/src/Repositories/Repository.php#L104

The API documentation you linked is simply a reference for each resource type, no examples are provided for GET/POST/PUT requests etc. If you can find those I can help further

**Comment by momon** [comment]
> 
> 
> @momon unfortunately I don't think this package will add support because it's not built directly into Kubernetes, it is an addon service.
> 
> However you should be able to use the client request methods directly to perform the API requests
> 
> I would take a look at this method:
> https://github.com/maclof/kubernetes-client/blob/master/src/Client.php#L321
> 
> You can see some examples of the methods usage here:
> https://github.com/maclof/kubernetes-client/blob/master/src/Repositories/Repository.php#L104
> 
> The API documentation you linked is simply a reference for each resource type, no examples are provided for GET/POST/PUT requests etc. If you can find those I can help further

Thanks for the response.  I will explore the method you suggested and see if that will sort it out for me.

I'm happy to research and find out the info you are asking as I would likely need the assistance, however I am not entirely sure I understand what sort of info it is exactly you are needing since I don't even understand what exactly is a "plugin" in this kubernetes environment.  Are you refering to cert-manager maybe?

From reading https://github.com/ahmetb/gke-letsencrypt (which is what I used as a reference), the solution is composed of https://letsencrypt.org/ (setup as a provider) and https://github.com/jetstack/cert-manager/ which is what does the communication with set provider.  So I am guessing the plugin here is cert manager which is located here:

https://github.com/jetstack/cert-manager/

That being said, once there (assuming I am correct) I am a bit unclear on what exactly it is you would like to see.

Cheers and thanks again for your help.

**Comment by momon** [comment]
> @momon unfortunately I don't think this package will add support because it's not built directly into Kubernetes, it is an addon service.
> 
> However you should be able to use the client request methods directly to perform the API requests
> 
> I would take a look at this method:
> https://github.com/maclof/kubernetes-client/blob/master/src/Client.php#L321
> 
> You can see some examples of the methods usage here:
> https://github.com/maclof/kubernetes-client/blob/master/src/Repositories/Repository.php#L104
> 
> The API documentation you linked is simply a reference for each resource type, no examples are provided for GET/POST/PUT requests etc. If you can find those I can help further

@maclof I'm pretty sure I am doing all sorts of wrong here as I have not been able to troubleshoot much without an actual error message but I am hoping you can point me in the right direction.

Based on your links here is what I am trying to send:

`                $crt_data = array([
                    'kind'  =>  'Certificate',
                    'metadata' => [
                        'name' => $resourceData['name'],
                        'namespace' => 'default',
                        'labels' => [
                            'app'   =>  $label_name,
                            'abc-env' => $resourceData['labels']['abc-env'],
                        ],
                    ],
                    'spec'   => 
                    [
                        'secretName'   =>  $label_name.'-abc-tls',
                        'issuerRef' =>  [
                            'name'  => 'letsencrypt-prod',
                            'kind'  => 'ClusterIssuer',
                        ],
                        'commonName' =>  $domain_name,
                        'dnsNames' =>  [$domain_name],
                        'acme' =>  [
                            'config'    =>  [
                                'http01'    =>  [
                                    'ingress'   =>  'igs-'.$label_name
                                ],
                                'domains'    =>  [
                                    $domain_name
                                ],
                            ]
                        ]
                    ]
                ]);

                $output = $this->gke->sendRequest('POST', '/', null, $crt_data, true, 'certmanager.k8s.io/v1alpha1');`

When I execute this all I am getting is:

`An uncaught Exception was encountered
Type: Maclof\Kubernetes\Exceptions\BadRequestException

Message: 404 page not found

Filename: /home/***/web/***/vendor/maclof/kubernetes-client/src/Client.php

Line Number: 365

Backtrace:

File: /home/***/web/***/application/controllers/Gcloud.php
Line: 2030
Function: sendRequest

File: /home/***/web/***/application/controllers/Gcloud.php
Line: 697
Function: resourceCreate

File: /home/***/web/***/public_html/index.php
Line: 315
Function: require_once`

I reckon my array syntax might not be 100% correct as I did struggle with this before but at least I had some error messages that showed me where the issues where at and I could trace and figure out what to adjust.  However, in this case I am totally blind as I have no clue what the error is exactly and since I have no actual example to follow it becomes a bit difficult.

The method referenced here: https://github.com/maclof/kubernetes-client/blob/master/src/Repositories/Repository.php#L104 is a bit abstract since I have no clue what the uri and query are supposed to be (I am not sure that's the issue I am having).

I am hoping you can point me in the right direction.

Thanks!

**Comment by momon** [comment]
Ignore the above, I think I got it working after realizing I had a bit of a syntax error in my array declaration and using /certificates/ as the uri.

I should be able to finish off from this point forward.  Thanks again!

**Comment by maclof** [comment]
@momon keep me updated and let me know if you need anymore help, if you’ve figured out the uri then that’s the bit I couldn’t see from the documentation

**Comment by momon** [comment]
> @momon keep me updated and let me know if you need anymore help, if you’ve figured out the uri then that’s the bit I couldn’t see from the documentation

Sure thing, happy to share working code in case someone else is trying to achieve the same or similar:

```
                $crt_data = json_encode([
                    'apiVersion' => 'certmanager.k8s.io/v1alpha1',
                    'kind'  =>  'Certificate',
                    'metadata' => [
                        'name' => $resourceData['name'],
                        'namespace' => 'default',
                        'labels' => [
                            'app'   =>  $label_name,
                            'abc-env' => $resourceData['labels']['abc-env'],
                        ],
                    ],
                    'spec'   => 
                    [
                        'secretName'   =>  $label_name.'-abc-tls',
                        'issuerRef' =>  [
                            'name'  => 'letsencrypt-prod',
                            'kind'  => 'ClusterIssuer',
                        ],
                        'commonName' =>  $domain_name,
                        'dnsNames' =>  [$domain_name],
                        'acme' =>  [
                            'config'    =>  [
                                'http01'    =>  [
                                    'ingress'   =>  'igs-'.$resourceData['labels']['abc-label']
                                ],
                                'domains'    =>  [
                                    $domain_name
                                ],
                            ]
                        ]
                    ]
                ]);

                $output = $this->gke->sendRequest('POST', '/'.'certificates'.'/', null, $crt_data, true, 'certmanager.k8s.io/v1alpha1');
```

The correct uri is: /certificates/

$this->gke is your instance of: Maclof\Kubernetes\Client so that is: 

```
use Maclof\Kubernetes\Client;
....
        $this->gke = new Client($authentication);
```

I've omitted some variables in my example above but it should be obvious how it works.

Hopefully this helps someone.

I am now trying to figure out the equivalent function to describe the resource which I am guessing should be pretty similar but using GET as a method instead.  Will give that a try shortly and update here as needed.

**Comment by maclof** [comment]
@momon how did you get on with this? can I help any further?

**Comment by momon** [comment]
My apologies for not updating this before.  I did eventually get it working but I ended up NOT needing to do certificates after an upgrade to cert-manager which now handles certificate creation on its own, so I ended up not needing to do this process after all and just let cert-manager handle everything instead.
