### ISSUE TITLE
How to use the Kubernetes php client library

### ISSUE THREAD

**Issue by mutesasiratimo** [maclof/kubernetes-client#47]
I am working on some dashboard changes for my final year project but I am stuck. I cloned the dashboard files into my go path directory but I am not familiar with cleint-go. How can I use the php client libraries for dahsboard development. A detailed instruction would be helpful please.

**Comment by maclof** [comment]
Hi @mutesasiratimo 

Not really sure what you mean by this, you mention using a GO library? This is a PHP library and will not work with Golang

If you are however using PHP you'll need to require this as a dependency with composer and then refer to the "Basic usage" section of the readme

**Comment by mutesasiratimo** [comment]
Hi Marc. I need help with setting up the whole client library. If I am
using a local minkikube cluster, how can I set up the php client to work
work with it.
