### ISSUE TITLE
Yaml vs array

### ISSUE THREAD

**Issue by mnwalker** [maclof/kubernetes-client#48]
Not sure if already supported but been digging through code and not seen anyway of doing this yet (let me know if it already works!)

Readme details how to build a replication controller (or any other item) through an array, but for the purposes of being compatible outside PHP I would rather work purely with YAML.
I plan to write, manage and save YAML files through my app and would rather be able to pass in a pure YAML template instead of an array.
That way I could if needed edit yamls with a text editor and run manually on exact same config with kubectl.

If not YAML then could potentially use json instead, just a personal preference for yaml over json.
Key is being able to load/output configuration via a text file and then use the client as normal.

**Comment by mikemilano** [comment]
Have you moved forward with this plan? I was wondering if you parsed yaml into an array, if the result work without any more modifications.

If the config were dynamic, you could run the yaml files through twig before processing too.

I don't necessarily need to run the yaml direct. I just think it would be more intuitive to maintain/migrate the manifests this way.

**Comment by vagkaefer** [comment]
Before using the project, I was also interested in using the YAML files.

But, if you want to integrate the database, it will be easier to work with the approximation of variables.

I couldn't test it, but you can create a function that transcribes YAML, transforming YAML-> JSON-> VARIABLES or YAML-> JSON and use it directly in the API (I didn't look at the project source to confirm this).

Can you better inform what your need is? To confirm that using .yaml files is the best way for you?

**Comment by mikemilano** [comment]
> Can you better inform what your need is? To confirm that using .yaml files is the best way for you?

@vagkaefer My initial thoughts were based on design & communication around K8s config given that YAML is a pretty ubiquitous format to work with. It would make it easier to use existing configs, and reason/communicate about config with others who may not be fluid in PHP.

That said, working with config as PHP arrays isn't that bad, and as you point out, has advantages depending how you're using it.

**Comment by maclof** [comment]
As per my latest commit https://github.com/maclof/kubernetes-client/commit/204ef0e77f570e5ebb6f667a7d051cfb65ffb91e

You can now specify the attributes of a model is either an array, yaml or json.

Simply specify the data type as the second parameter to the model constructor, for example:

```php
use Maclof\Kubernetes\Models\Pod;

$yaml = '
apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: test
  labels:
    label: test
';

$pod = new Pod($yaml, 'yaml');
```

I am just waiting for tests to complete, I'll fix any failures then release a new version including this change shortly.

**Comment by maclof** [comment]
Release 0.17.0 includes this functionality
