### ISSUE TITLE
Service Account Authentication

### ISSUE THREAD

**Issue by jleavers** [maclof/kubernetes-client#5]
I tested a script from within a pod using a service account, i.e.

```
$client = new Client([
    'master'  => 'https://master.mycluster.com',
    'ca_cert' => '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt',
    'token'   => '/var/run/secrets/kubernetes.io/serviceaccount/token',
]);
```

However I got a `GuzzleHttp\Exception\ClientException` with the standard "Unauthorized" message.

A basic test with curl from the pod worked, i.e.

```
curl -v --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes/
```

So I echoed the contents of the `createGuzzleClient` options:

```
Array
(
    [headers] => Array
        (
            [Content-Type] => application/json
            [Authorization] => Bearer /var/run/secrets/kubernetes.io/serviceaccount/token
        )

    [verify] => /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    [base_uri] => https://kubernetes
)
```

Should the contents of the token be shown in `[Authorization]` as opposed to the filename?

I ask because I worked around the problem by passing the contents of the token as opposed to the filename.

```
$client = new Client([
    'master'  => 'https://master.mycluster.com',
    'ca_cert' => '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt',
    'token'   => file_get_contents('/var/run/secrets/kubernetes.io/serviceaccount/token'),
]);
```

**Comment by maclof** [comment]
@jleavers sorry it took so long to fix this, but as of v0.2.5 you can provide either the path to the token or the contents of the token and it should handle both scenarios.

Any problems please raise another issue.
