### ISSUE TITLE
Authenticating to Google Cloud Kubernetes

### ISSUE THREAD

**Issue by Radiergummi** [maclof/kubernetes-client#51]
I struggle with setting up authentication to our GKE cluster. Neither using the credentials provided in the Cloud Console (username/password) nor IAM service account certificates (ca_cert/client_cert/client_key) seem to work, both result in a 403 response saying system: anonymous has been denied access.  
Which credentials does your library require, and where do I need to obtain them?

**Comment by maclof** [comment]
Hi @Radiergummi 

We do have a few people using this client with GKE, although I cannot say for sure how they're authenticating.

As long as you have the correct address/port for the master server and either a valid username/password or certificates then you should be good.

This library supports basic auth, certificate auth and token auth.

**Comment by Radiergummi** [comment]
Hey @maclof I finally resorted to writing my own socket based client which authenticates via Basic auth, though I cannot really say what I'm doing different aside from using raw sockets instead of Guzzle.  
What I noticed: All GKE clusters have a self-signed certificate. This requires to set Guzzles `verify` option to false, so you need to supply a custom client instance to your Kubernetes client. That, however, will break URL construction, so I had to fiddle around with the Guzzle options to set the base URL too. Possibly there are some options you set on the client that I missed. I would love to keep on digging into this but I don't have the time currently :(  
Anyway thank you for your response!

**Comment by maclof** [comment]
@Radiergummi no need to provide a custom instance of Guzzle, there is a "verify" option you can already supply to the client when you initialise it.

For example:
`
$client = new Client([
  'master' => 'https://gkemaster.google.com',
  'verify' => false,
]);
`
