### ISSUE TITLE
can i just get the api by kubeconfig file, cause i dont know how to get token and crt info by this file

### ISSUE THREAD

**Issue by papillonyi** [maclof/kubernetes-client#56]

**Comment by maclof** [comment]
@papillonyi sorry for the delay with this issue, can you provide an example of your kubeconfig file? Please replace any sensitive info with an X

**Comment by maclof** [comment]
@papillonyi this is now supported if your Kubeconfig file has users defined. If it uses tokens I will need an example of this format as per my previous comment. An example is provided below either providing the Kubeconfig data directly or as a file path. If you provide the data directly it defaults to expecting yaml, if you want to specify as either json or an array you can change the second attribute of the setOptionsFromKubeconfig method call.

```php
use Maclof\Kubernetes\Client;

$client = new Client;

$client->setOptionsFromKubeconfig($kubeconfigData);

// or

$client->setOptionsFromKubeconfigFile($kubeconfigFilePath);
```
