### ISSUE TITLE
Update Ingress support for kubernetes version 1.18 

### ISSUE THREAD

**Issue by GooseCoder** [maclof/kubernetes-client#62]
I got an error when trying the library with Kubernetes version 1.18, digging up it seems that the API  call has changed from "extensions" to "networking.k8s.io" on the Ingress resource spec. The Ingress Model class should be updated to match this. Btw good job with the library I use it for a variety of projects. Regards

**Comment by maclof** [comment]
I have made a comment in your pull request regarding this
