### ISSUE TITLE
using kubeconfig results in empty guzzle client

### ISSUE THREAD

**Issue by josefschabasser** [maclof/kubernetes-client#70]
Hello!

I realized 2 things:
First, there is a typo in [src/Client.php on line 202](https://github.com/maclof/kubernetes-client/blob/591bd14e1d1f1ca3485486016741e8265b86f8d3/src/Client.php#L202):
```
$this->cientKey = null;
```
should be
```
$this->clientKey = null;
```
Second, using `setOptionsFromKubeconfig` or `setOptionsFromKubeconfigFile` result in an empty guzzleClient because it is initialized in the constructor (with empty options array) before `setOptions` on line [351](https://github.com/maclof/kubernetes-client/blob/591bd14e1d1f1ca3485486016741e8265b86f8d3/src/Client.php#L351) (which is resetting all options, but not re-initializing guzzleClient). This can be prevented by adding `$this->guzzleClient = $this->createGuzzleClient();` to the end of `setOptionsFromKubeconfig`.

Best regards
Josef

**Comment by maclof** [comment]
@josefschabasser thank you! this is fixed in version 0.18.3
