### ISSUE TITLE
upgrade requests don't work if using kubeconfig file/data

### ISSUE THREAD

**Issue by josefschabasser** [maclof/kubernetes-client#71]
Hi!

I know, this comes a bit late. I found another issue with `setOptionsFromKubeconfig`. On line [338](https://github.com/maclof/kubernetes-client/blob/238b056168375f1f762bae95474eb099a02b835a/src/Client.php#L338), the CA certificate is assigned to `$options['verify']` which will break upgrade requests. If it is assigned to `$options['ca_cert']`, upgrade requests work fine.

Please change line 338 from
```
$options['verify'] = $this->getTempFilePath('ca-cert.pem', base64_decode($cluster['certificate-authority-data'], true));
```
to
```
$options['ca_cert'] = $this->getTempFilePath('ca-cert.pem', base64_decode($cluster['certificate-authority-data'], true));
```

I tested this with kubeconfig files generated with azure-cli (`az aks get-credentials`).

Best regards
Josef

**Comment by Altyon** [comment]
Same problem here. Even by changing the line I still get the error

**Comment by josefschabasser** [comment]
Strange, for me it works with this change.

**Comment by josefschabasser** [comment]
@maclof shameless bump

**Comment by maclof** [comment]
@josefschabasser I merged your PR this morning. Please retest
