### ISSUE TITLE
README for service account appears to be wrong

### ISSUE THREAD

**Issue by addshore** [maclof/kubernetes-client#82]
Use of a service account in the latest release suggests the following:

```php
use Maclof\Kubernetes\Client;
use Http\Adapter\Guzzle6\Client as Guzzle6Client;
$httpClient = Guzzle6Client::createWithConfig([
	'verify' => '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt',
]);
$client = new Client([
	'master' => 'https://master.mycluster.com',
	'token' => '/var/run/secrets/kubernetes.io/serviceaccount/token',
], null, $httpClient);
```

However Client constructor is
```php
	public function __construct(array $options = array(), GuzzleClient $guzzleClient = null, RepositoryRegistry $repositoryRegistry = null)
```

So the example is using `Guzzle6Client::createWithConfig` to get a `Http\Adapter\Guzzle6\Client` object.
This implements implements `Http\Client\HttpClient`, `Http\Client\HttpAsyncClient` which in tern implements `Psr\Http\Client\ClientInterface` and `Psr\Http\Client\HttpAsyncClient`
It is then passing this as the 3rd parameter which is expecting a `RepositoryRegistry` which definitely looks wrong

It looks like this should instead be the second parameter?
But even that looks a little wrong as the doc suggests `\GuzzleHttp\Client` but is type hinted to `GuzzleHttp\Client\GuzzleClient` which implements `\GuzzleHttp\ClientInterface`

The default behaviour does indeed make a `\GuzzleHttp\Client\GuzzleClient` via `createGuzzleClient`, so it seems like this would be right.
The `Http\Adapter\Guzzle6\Client` seems to make and use a `GuzzleClient` internally, but this isn't accessible to `Maclof\Kubernetes\Client`

So should the use of the adapter just be removed, and instead a guzzle client just be passed right in?

**Comment by addshore** [comment]
So this would end up looking a little more like:

```
        $guzzleConfig =[
            'verify' => '/var/run/secrets/kubernetes.io/serviceaccount/ca.crt',
        ];
        $guzzleHandlerStack = new HandlerStack(\GuzzleHttp\choose_handler());
        $guzzleHandlerStack->push(Middleware::prepareBody(), 'prepare_body');
        $guzzleConfig = array_merge(['handler' => $guzzleHandlerStack], $guzzleConfig);
        $httpClient = new GuzzleClient($guzzleConfig);

        $client = new Client([
            // Service host per: https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/#accessing-the-api-from-a-pod
            'master' => 'https://kubernetes.default.svc',
            'token'   => '/var/run/secrets/kubernetes.io/serviceaccount/token',
        ], $httpClient);
```
(Though some convenience method could be added for this?)

**Comment by maclof** [comment]
Hi @addshore you are comparing the master branch documentation versus the v0.21.0 code, the documentation you should refer to is here: https://github.com/maclof/kubernetes-client/tree/0.21.0

Guzzle is removed as a dependency in the master branch and will be in the next release, to continue using Guzzle at that point you need to use the Guzzle http adapter (or any other http adapter for that matter)

**Comment by addshore** [comment]
Gosh darnit, I thought I checked this!
