### ISSUE TITLE
illuminate/support version can be 4.x

### ISSUE THREAD

**Issue by danielsmithsd** [maclof/kubernetes-client#9]
Wondering if there is a reason illuminate/support is required to be 5.x?

I'm currently using this in production with illuminate/support v4 and haven't run into any issues.  I'm not super familiar with composer, but was wondering if it would be possible to change the version requirement for illuminate/support to allow 4.x but install 5.x if it's not already a part of the project.

**Comment by maclof** [comment]
Hey @danielsmithsd 

That should definitely be possible, I think the only thing we're actually using illuminate/support for is the collection class, which should be fine with 4.x

I'll check this tomorrow and create a PR for it.

**Comment by danielsmithsd** [comment]
Agreed on the usage.  I dug in to see if it would be an issue and didn't think it would because collections (as far as I know) haven't changed much in a long time.  Thanks much!  I hate to maintain a fork for something so simple.

Also, feel lame not submitting a PR myself, but I'm not confident on the "use 5 is 4 isn't already installed" part.

Thanks!

**Comment by maclof** [comment]
This has been tested in Laravel v4.2.11 and is now fixed as of v0.2.4

Any problems please do not hesitate to raise another issue.
